---
abstract: 'Simple Interface To q4m'
author:
  - 'Copyright (c) 2008 Daisuke Maki <daisuke@endeworks.jp>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Queue-Q4M
no_index:
  directory:
    - misc
    - inc
    - t
requires:
  DBI: 0
  Mouse: 0.13
  SQL::Abstract: 0
  Scope::Guard: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.00015
