---
abstract: 'Simple Interface To q4m'
author:
  - 'Copyright (c) 2008 Daisuke Maki <daisuke@endeworks.jp>'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Queue-Q4M
no_index:
  directory:
    - misc
    - inc
    - t
requires:
  DBI: 0
  Moose: 0
  SQL::Abstract: 0
  Scope::Guard: 0
version: 0.00010
